@baseURL = http://localhost:4000/api/produtos

// GET - Lista todos os produtos
GET {{baseURL}}
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjU1ZjkwNDkzYTVkNjliMzlmZjJhMGMxIn0sImlhdCI6MTcwMDc2MTY5NiwiZXhwIjoxNzAxMDIwODk2fQ.OTue-iPOv0HRGVBWLPQ5KSJdtXdugCKB5AV-6p1WxIE

###
// GET - Lista de produto pela id
GET {{baseURL}}/id/655f9448090346d22f28eca4
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjU1ZjkwNDkzYTVkNjliMzlmZjJhMGMxIn0sImlhdCI6MTcwMDc2MTY5NiwiZXhwIjoxNzAxMDIwODk2fQ.OTue-iPOv0HRGVBWLPQ5KSJdtXdugCKB5AV-6p1WxIE

###
// GET - Lista de produto pelo nome do produto ou marca
GET {{baseURL}}/produto/Razer
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjU1ZjkwNDkzYTVkNjliMzlmZjJhMGMxIn0sImlhdCI6MTcwMDc2MTY5NiwiZXhwIjoxNzAxMDIwODk2fQ.OTue-iPOv0HRGVBWLPQ5KSJdtXdugCKB5AV-6p1WxIE

###
// GET - Lista de produto com o preço maximo e classificação mínima
GET {{baseURL}}/produtos-filtrados?precoMax=69.99&classificacaoMin=4
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjU1ZjkwNDkzYTVkNjliMzlmZjJhMGMxIn0sImlhdCI6MTcwMDc2MTY5NiwiZXhwIjoxNzAxMDIwODk2fQ.OTue-iPOv0HRGVBWLPQ5KSJdtXdugCKB5AV-6p1WxIE

###
// POST - Insere um novo registro
POST {{baseURL}}
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjU1ZjkwNDkzYTVkNjliMzlmZjJhMGMxIn0sImlhdCI6MTcwMDc2MTY5NiwiZXhwIjoxNzAxMDIwODk2fQ.OTue-iPOv0HRGVBWLPQ5KSJdtXdugCKB5AV-6p1WxIE

{
  "produto": "Mouse Gamer",
  "marca": "Razer",
  "preco": 69.99,
  "estoque": 50,
  "cor": "Preto",
  "data_lancamento": "2022-09-30",
  "classificacao": 4,
  "peso": 0.2
}

###
// PUT - Altera o registro
PUT {{baseURL}}
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjU1ZjkwNDkzYTVkNjliMzlmZjJhMGMxIn0sImlhdCI6MTcwMDc2MTY5NiwiZXhwIjoxNzAxMDIwODk2fQ.OTue-iPOv0HRGVBWLPQ5KSJdtXdugCKB5AV-6p1WxIE

{
    "_id": "655f9448090346d22f28eca4",
    "produto": "Mouse Gamer",
    "marca": "Razer",
    "preco": 69.99,
    "estoque": 40,
    "cor": "Preto",
    "data_lancamento": "2022-09-30",
    "classificacao": 4,
    "peso": 0.2
}

###
// DELETE - Apaga um registro pela id
DELETE {{baseURL}}/655f9448090346d22f28eca4
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjU1ZjkwNDkzYTVkNjliMzlmZjJhMGMxIn0sImlhdCI6MTcwMDc2MTY5NiwiZXhwIjoxNzAxMDIwODk2fQ.OTue-iPOv0HRGVBWLPQ5KSJdtXdugCKB5AV-6p1WxIE
